# docker-compose.yml
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: inout
      POSTGRES_PASSWORD: inoutpwd
      POSTGRES_DB: inoutdb
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.test
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports: ["5050:80"]
volumes:
  pgdata:
